Textual changes for 8-th day
gregurco/jobeet-tutorial pull request #14
Opened 2018-08-04 19:47 UTC by slash3b

Please note that some of the textual changes are rather intuitive, my English got a bit rusty over recent years : )

2018-08-05 19:20 UTC, gregurco commented on docs/days/day-8.md
> +     * Publish job entity.
Let's discuss this change tomorrow over a cup of coffee because it's not the only place where I have the same `a` and probably I have to change it at once in code :slightly_smiling_face:

2018-08-06 20:29 UTC, gregurco requested changes

2018-08-06 20:29 UTC, gregurco commented on docs/days/day-8.md
> +     * Publish job entity.
I read a little bit about this stuff. Could you please revert this change and I will merge the PR :slightly_smiling_face:

2018-08-07 09:25 UTC, slash3b commented
yes, sure, will do it tonight : )

On 6 August 2018 at 23:29, Vlad Gregurco <notifications@github.com> wrote:

> *@gregurco* requested changes on this pull request.
> ------------------------------
>
> In docs/days/day-8.md
> <https://github.com/gregurco/jobeet-tutorial/pull/14#discussion_r208019381>
> :
>
> > @@ -1295,7 +1295,7 @@ class JobController extends AbstractController
>      // ...
>
>      /**
> -     * Publish a job entity.
> +     * Publish job entity.
>
> I read a little bit about this stuff. Could you please revert this change
> and I will merge the PR 🙂
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gregurco/jobeet-tutorial/pull/14#pullrequestreview-143748452>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADHjxY6uVpezjbsu8NZyoaUOMCoPDH8Dks5uOKdDgaJpZM4VvHhj>
> .
>

2018-08-07 21:20 UTC, slash3b commented
@gregurco please check amended commit

2018-08-07 21:22 UTC, gregurco commented
@slash3b it's good :+1: thank you!

2018-08-07 21:22 UTC, merged

2018-08-07 21:28 UTC, slash3b commented
O_O thanks

2018-08-07 21:44 UTC, gregurco commented
I also updated the code: https://github.com/gregurco/jobeet/blob/day8/src/Entity/Job.php#L15
:slightly_smiling_face: